### ISSUE TITLE
预设加载失败:local variable 'switch' referenced before assignment

### ISSUE THREAD

**Issue by HugeCodeInjecting** [YYuX-1145/Srt-AI-Voice-Assistant#22]
可以保存预设，savedate文件夹也有相应文件，但预设加载失败。
请大佬帮忙，非常感谢！！

**Comment by YYuX-1145** [comment]
可以提供完整的报错信息吗

**Comment by HugeCodeInjecting** [comment]
> 可以提供完整的报错信息吗
命令行窗口就这么一个错误信息，不知道是不是对应的错误。

[ERROR][2024-11-26_18:10:51]:default_exception_handler: Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 81, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by YYuX-1145** [comment]
感谢反馈。看上去你没有填写模型路径，如果你使用代码版，更新一下看看是否能正确加载预设？或者填入有效的模型路径重新保存一下

**Comment by HugeCodeInjecting** [comment]
> 感谢反馈。看上去你没有填写模型路径，如果你使用代码版，更新一下看看是否能正确加载预设？或者填入有效的模型路径重新保存一下

作者大大你好，我用的默认模型，是要选择这个路径下的文件吗？

D:\AI\GPT-SoVITS-v2-240821\GPT_SoVITS\pretrained_models\gsv-v2final-pretrained
![image](https://github.com/user-attachments/assets/932099fc-8736-41ea-9701-315d5b499832)

**Comment by HugeCodeInjecting** [comment]
> s1bert对应GPT模型，S2G对应Sovits模型。如果你使用的是代码版，更新后应该可以不填

感谢作者大大，已经加载成功了，
我用的打包版。
